fib = int(input("Enter the number of months: "))
a = 0
b = 1
sum = 0
count = 1
print("Fibonacci: ", end = " ")
while(count <= fib):
  print(sum, end = " ")
  count = count + 1
  a = b
  b = sum
  sum = a + b
